# This file was generated by GoReleaser. DO NOT EDIT.
cask "ainfra" do
  version "0.2.27"

  on_macos do
    on_intel do
      sha256 "66bf99c6611c6a82d13292c23929e0143fe34d964442014f140da31180b66002"
      url "https://github.com/MHilhorst/ainfra/releases/download/v#{version}/ainfra_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0bb5e1552e38f6b1159f48328782a229131b27522600822378dbca42907f311a"
      url "https://github.com/MHilhorst/ainfra/releases/download/v#{version}/ainfra_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e7175c3b707de65600df93ad911d54a426f5629520bd08ea546227c3f6c86fde"
      url "https://github.com/MHilhorst/ainfra/releases/download/v#{version}/ainfra_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0902c6f5e7a716a297db5a21c16f6395268f7340f648b428e03cf4bbb1799e60"
      url "https://github.com/MHilhorst/ainfra/releases/download/v#{version}/ainfra_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ainfra"
  desc "Declarative infrastructure ownership manifests"
  homepage "https://github.com/MHilhorst/ainfra"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ainfra"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ainfra"]
    end
  end

  # No zap stanza required

end
