# This file was generated by GoReleaser. DO NOT EDIT.
cask "ainfra" do
  version "0.2.12"

  on_macos do
    on_intel do
      sha256 "1b2eab0df71cfa3d4cabaa5f1770cce154c1846eea771bae9ec1186a6e9cd2bf"
      url "https://github.com/MHilhorst/ainfra/releases/download/v#{version}/ainfra_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1cd96120c2a786e99d36f2bd0e601bb814590bc0025d0873b84860fda2e8fad4"
      url "https://github.com/MHilhorst/ainfra/releases/download/v#{version}/ainfra_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5ef1912b6128afce08dda2f90346811cb4b4579733326b834e35862523ee51b9"
      url "https://github.com/MHilhorst/ainfra/releases/download/v#{version}/ainfra_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b3b72df0ee41db54a17cf74237ea3ad6419cc86c71459b54644a56ae495ed1d"
      url "https://github.com/MHilhorst/ainfra/releases/download/v#{version}/ainfra_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ainfra"
  desc "Declarative infrastructure ownership manifests"
  homepage "https://github.com/MHilhorst/ainfra"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ainfra"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ainfra"]
    end
  end

  # No zap stanza required

end
