# This file was generated by GoReleaser. DO NOT EDIT.
cask "ainfra" do
  version "0.2.8"

  on_macos do
    on_intel do
      sha256 "8cea875db36eb7e42edacbeceb1906a81a8dee69f9b929f38c07633b4c54e1ed"
      url "https://github.com/MHilhorst/ainfra/releases/download/v#{version}/ainfra_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6a412aaa68deb335cdbead2c19bd73e7aeadcbcfd4b3c233dc99dc5298327340"
      url "https://github.com/MHilhorst/ainfra/releases/download/v#{version}/ainfra_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1841b8383aee591f8d0e0a80e61009ccaaa50d1cd9a065eae9b4252ed2e88613"
      url "https://github.com/MHilhorst/ainfra/releases/download/v#{version}/ainfra_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "41eeec692f2b27e878a630ea65edc8a1ab97429ac589170e00d76519b806cce7"
      url "https://github.com/MHilhorst/ainfra/releases/download/v#{version}/ainfra_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ainfra"
  desc "Declarative infrastructure ownership manifests"
  homepage "https://github.com/MHilhorst/ainfra"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ainfra"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ainfra"]
    end
  end

  # No zap stanza required

end
